### ISSUE TITLE
Error when launching tracker after loading overlay layout .ini

### ISSUE THREAD

**Issue by DerDrach** [TalicZealot/SotnRandoTools#43]
Please use this template for any bugs or problems you encounter using the tools and label the issue appropriately. Fill as many of the fields listed below as possible.

# Error:
![EmuHawk_DcsAuYsqvg](https://github.com/TalicZealot/SotnRandoTools/assets/149031389/d0ba6747-c75c-4ead-8d51-8088022d4797)

Attached txt files with the output of the errors.
[Launch Tracker Error.txt](https://github.com/user-attachments/files/15901602/Launch.Tracker.Error.txt)
[Close RandoTools Error.txt](https://github.com/user-attachments/files/15901605/Close.RandoTools.Error.txt)
[Close Autotracker Error.txt](https://github.com/user-attachments/files/15901606/Close.Autotracker.Error.txt)

# Bug description:
When attempting to load any custom layout .ini it throws an error and opens a blank Autotracker window. It throws 2 more errors when attempting to close the Autotracker window or the Randotools itself. 

# How to reproduce:
Load any layout .ini file including the bundled Default.ini and then click Launch Tracker

# Additional context, screenshot or log file from /ExternalTools/SotnRandoTools/Logs/:
I have confirmed with at least 2 others that they experience the same issue when trying to use custom layouts.

# SotnRandoTools version:
1.7.0

# BizHawk version:
2.9.1

# Seed Information:
N/A

# Randomizer version:
N/A

# Operating system and version:
Windows 10 Version 22H2 10.0.19045 Build 19045

**Comment by TalicZealot** [comment]
Can't replicate. Try to delete ToolConfig.ini

**Comment by TalicZealot** [comment]
I think this might have already been addressed in the version that isn't released yet.

**Comment by DerDrach** [comment]
Issue persists after deleting the ToolConfig.ini. I can also reproduce it on a fresh install of bizhawk and the randotools. Use Overlay does have to be checked for it to throw the error.

**Comment by TalicZealot** [comment]
This should be addressed once I release the new version with the other fixes.

**Comment by TalicZealot** [comment]
I'm not sure what was causing this, but it should be gone in 1.7.1, will reopen if issue persists.
